spring.application.name=app_backend

# Connect to DB
spring.datasource.url=dbc:postgresql://localhost:5435/sportgis_db
spring.datasource.username=postgres
spring.datasource.password=Secret
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate options
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Hibernate table upd
spring.jpa.hibernate.ddl-auto=update

# SQL-request LOGGING
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
